config/routes.rb
Rails.application.routes.draw do
  resources :orders

  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :users
  root 'store#index'

  get 'dashboard' => 'store#dashboard'

  get 'recommendations' => 'recommendations#rees46_recommender'

  resources :categories

  resources :brands

  resources :products do
    collection { post :import }
  end

  resources :line_items, only: [:create, :destroy] do
    get 'increment', on: :member
    get 'decrement', on: :member
  end

  resources :carts, only: [:index, :show, :destroy]

  resources :parsers, only: :index
  get 'store/xml_rees46'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def total_price
    line_items.to_a.sum(&:total_price)
  end

  def total_quantity
    line_items.to_a.sum(&:total_quantity)
  end

  def product_ids_in_cart
    line_items.select(&:product_id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :destroy]

  def show
    unless @cart.line_items.present?
      @cart.destroy if @cart.id == session[:cart_id]
      session[:cart_id] = nil
      redirect_to root_path, notice: t('cart.notice_controller')
    end
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    redirect_to root_path, notice: t('cart.notice_controller')
  end

  private

  def set_cart
    @cart = Cart.find(params[:id])
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_list.slim
div class="row row_#{item.id}"
  .col-md-6
    .row
      .col-md-3
        = link_to image_tag(item.product.image.medium, class: "img-responsive"), product_path(item.product)
      .col-md-3 style="width: 350px;"
        p= link_to item.product.title, product_path(item.product)

  .col-md-2
    - if item.product.size && Product::SIZES.keys[item.product.size].present?
      li= t('product.pro_size').values[item.product.size]
      li= Product.const_get(Product::SIZES.keys[item.product.size].gsub(' ', '_').upcase).keys[item.size_id]
    - elsif item.product.child_ages && Product::AGE_SIZES.keys[item.product.child_ages].present? 
      li= Product::AGE_SIZES.key(item.size_id)
    - elsif item.size_id && Product::PART_TYPES.keys[item.product.part_types[item.size_id.to_i]].present?

  .col-md-2
    .qty
      span.qt-minus.remove_single_from_cart_decrement
        = link_to "-", decrement_line_item_path(item), remote: true
      span.qt
        div class="quantity_#{item.id}"
          = item.quantity
      span.qt-plus
        = link_to "+", increment_line_item_path(item), remote: true

  .col-md-2.item-total
    p class="item_total_#{item.id} delete-inline"
      = number_to_currency(item.total_price,  unit: "₽ ")
    .remove_single_from_cart_delete
      = button_to "X", line_item_path(item), method: :delete, class: "del"
hr

javascript:
  function afterInitRees46() {
   REES46.addReadyListener(function () {
     $('.remove_single_from_cart_decrement').click(function () {
       if ($(this).next().text() == 1) {
         REES46.pushData('remove_from_cart', {
           item_id: '#{item.product_id}',
           price: '#{item.product.price}',
           is_available: '#{item.product.available?}',
           categories: '#{item.product.category_id}'
         });
       };
     });
   });

   REES46.addReadyListener(function () {
     $('.remove_single_from_cart_delete').click(function () {
       REES46.pushData('remove_from_cart', {
         item_id: '#{item.product_id}',
         price: '#{item.product.price}',
         is_available: '#{item.product.available?}',
         categories: '#{item.product.category_id}'
       });
     });
   });
  };

app/views/carts/cart_urls.js.erb
<% if (@recommender == 'see_also') %>
$('#recommender_see_also').html("<%= j render(partial: 'rees46_see_also.slim', locals: { products: @products, recommender: @recommender }) %>");
var elem = document.querySelector('.delayed-sa-flickity');
var flkty = new Flickity( elem, {
  cellAlign: 'left'
});
<% end %>

app/views/carts/get_cart_uls.js.erb
jQuery('#recommender_see_also').html("<%= j render(partial: 'rees46_see_also.slim', locals: { products: @products, recommender: @recommender }) %>");

app/views/carts/get_cart_urls.js.erb
<% if (@recommender == 'see_also') %>
jQuery('#recommender_see_also').html("<%= j render(partial: 'rees46_see_also.slim', locals: { products: @products, recommender: @recommender }) %>");
<% end %>

app/views/carts/rees46_see_also.slim
h1 Similar products

- products.take(4).each do |product|
  .col-md-3
    = link_to product.title, product_path(product, recommdend_by: @recommender)
    = image_tag(product.image.thumb, class: "img-responsive")
    = product.price

app/views/carts/show.slim
.col-md-12.s_border
  h2.sh = t('cart.title')
  hr
  .row
    .col-md-6
      h5.text-center = t('cart.items')
    .col-md-2
      h5.text-center = t('cart.sizes')
    .col-md-2
      h5.text-center = t('cart.qty')
    .col-md-2
      h5.text-center = t('cart.price')

  hr
  = render partial: "cart_list", collection: @cart.line_items.order(:id), as: :item

  h2.text-right.cart_total = t('cart.total') + " " + "#{number_to_currency(@cart.total_price,  unit: "₽ ")}"

  .col-md-4.text-center.cart-buttons
    = link_to t('cart.root_path'), root_path, class: "btn btn-primary"
  .col-md-4.text-center.cart-buttons
    = button_to t('cart.new_order'), new_order_path, method: :get, class: "btn btn-success"
  .col-md-4.text-center.cart-buttons
    = button_to t('cart.empty'), @cart, method: :delete, data: { confirm: t('simple_form.confirmation') }, class: "btn btn-danger"

.clr

div class="rees46-recommend" data-type="see_also" data-limit="12" data-title="Посмотрите также"