config/routes.rb
Rails.application.routes.draw do
  resources :orders

  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :users
  root 'store#index'

  get 'dashboard' => 'store#dashboard'

  get 'recommendations' => 'recommendations#rees46_recommender'

  resources :categories

  resources :brands

  resources :products do
    collection { post :import }
  end

  resources :line_items, only: [:create, :destroy] do
    get 'increment', on: :member
    get 'decrement', on: :member
  end

  resources :carts, only: [:index, :show, :destroy]

  resources :parsers, only: :index
  get 'store/xml_rees46'
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products
  validates :name, presence: true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :find_brand, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :admin_permission, except: :show

  def index
    @brands = Brand.all
  end

  def show
    @products = @brand.products
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to brands_path, notice: t('controller.brands.create.notice')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @brand.update_attributes(brand_params)
      redirect_to brands_path, notice: t('controller.brands.update.notice')
    else
      render :edit
    end
  end

  def destroy
    if @brand.destroy
      redirect_to brands_path, notice: t('controlle.brands.destroy.notice.destroy')
    else
      redirect_to brands_path, notice: t('controlle.brands.destroy.notice_brands_path')
    end
  end

  private

  def admin_permission
    if current_user && current_user.has_role?(:admin)
      true
    else
      redirect_to root_path
    end
  end

  def find_brand
    @brand = Brand.find(params[:id])
  end

  def brand_params
    params.require(:brand).permit(:name)
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.slim
.col-md-6.col-xs-offset-3
  h1 = t('brand.new_brand')
  br
  = simple_form_for @brand do |f|
    = f.input :name

    = f.submit t('brand.edit.save'), class: 'btn btn-success'

app/views/brands/_index.slim
.col-md-3.col-sm-4.col-xs-6
  br
  li= brand.name
  = link_to t('simple_form.edit'), edit_brand_path(brand), class: 'btn btn-primary', style: "margin-right: 15px;"
  = link_to t('simple_form.delete'), brand, method: :delete, data: { confirm: t('simple_form.confirmation') }, class: "btn btn-danger"

app/views/brands/_product_brand.slim
.col-md-3.col-sm-4.col-xs-6.carousel-cell
  .r-product-item
    .picture
      = link_to image_tag(product.image.thumbs), product_path(product, recommdend_by: @recommender)
    .title
      = link_to product.title.truncate(40), product_path(product)
    .price
      = number_to_currency(product.price,  unit: "₽ ", precision: 0)

app/views/brands/edit.slim
.col-md-6.col-xs-offset-3
  h1.text-center= t('brand.edit_brand')
  = render 'form'

app/views/brands/index.slim
.container
  .row
    .col-md-6
      h1 = t('brand.title')
    .col-md-6.brand-add-button
      = link_to new_brand_path, class: "btn btn-success pull-right" do
        span.glyphicon.glyphicon-plus
        = t('brand.new_brand')
  hr
    = render partial: 'brands/index', collection: @brands, as: :brand

app/views/brands/new.slim
.col-xs-10.col-xs-offset-1
  = render 'form'

app/views/brands/show.slim
h1  Brand #{@brand.name}

= render partial: 'brands/product_brand',  collection: @products, as: product