config/routes.rb
Rails.application.routes.draw do
  resources :orders

  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :users
  root 'store#index'

  get 'dashboard' => 'store#dashboard'

  get 'recommendations' => 'recommendations#rees46_recommender'

  resources :categories

  resources :brands

  resources :products do
    collection { post :import }
  end

  resources :line_items, only: [:create, :destroy] do
    get 'increment', on: :member
    get 'decrement', on: :member
  end

  resources :carts, only: [:index, :show, :destroy]

  resources :parsers, only: :index
  get 'store/xml_rees46'
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend ActsAsTree::TreeWalker
  extend ActsAsTree::TreeView
  extend FriendlyId

  enum hide: [:no, :yes]

  acts_as_tree order: 'name'

  friendly_id :name, use: :slugged

  has_many :products
  has_many :children, class_name: 'Category', foreign_key: :parent_id, dependent: :destroy
  belongs_to :parent, class_name: 'Category'

  validates :name, presence: true

  def human_categories_industry
    if categories_industry == 0
      return 'fashion'
    elsif categories_industry == 1
      return 'cosmetic'
    elsif categories_industry == 2
      return 'child'
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :categories_recommender]
  before_action :admin_permission, except: [:show, :categories_recommender]

  def index
    @categories = Category.where(parent_id: nil)
  end

  def show
    @categories = Category.all

    @products = @category.products.page(params[:page])
    if !@category.root?
      @products = Product.page(params[:page]).per(24)
    else @category.root?
         @products = Product.page(params[:page])
    end
    @categories = Category.where(parent_id: @category).page(params[:page])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: t('controller.categories.create.notice')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to categories_path, notice: t('controller.categories.update.notice')
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      redirect_to @category, notice: t('controller.brand.destroy.notice')
    else
      redirect_to root_path, notice: t('controller.categories.destroy.notice_root')
    end
  end

  private

  def admin_permission
    if current_user && current_user.has_role?(:admin)
      return true
    else
      redirect_to root_path
    end
  end

  def find_category
    @category = Category.friendly.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :parent_id, :categories_industry, :slug, :category_hide)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.slim
= simple_form_for @category do |f|
  = f.input :name
  = f.input :parent_id, as: :select, collection: Category.all
  = f.input :categories_industry, as: :select, collection: Product.industries
  = f.input :category_hide, as: :radio_buttons, include_hidden: false, collection: Category.hides, item_wrapper_class: 'radio-inline'

  = f.submit "Сохранить", :class => 'btn btn-primary'

app/views/categories/_index.slim
- Category.walk_tree do |c, level|
  tr
    td
      = link_to "#{'-> '*level}#{c.name}", category_path(c)
    td.text-center
      = link_to t('simple_form.edit'), edit_category_path(c), class: 'btn btn-primary'
    td.text-center
      = link_to t('simple_form.delete'), c, method: :delete, data: { confirm: t('simple_form.confirmation') }, class: "btn btn-danger"

app/views/categories/_product_categories.slim
.col-md-3.col-sm-4.col-xs-6
  .r-product-item
    .picture
      = link_to image_tag(product.image.thumbs), product_path(product, recommdend_by: @recommender)
    .title
      = link_to product.title.truncate(40), product_path(product)
    .price
      = number_to_currency(product.price,  unit: "₽ ", precision: 0)

app/views/categories/_recommend_cat_products.slim
- @products.each do |product|
  .col-md-3.col-sm-4.col-xs-6
    .r-product-item
      .picture
        = link_to image_tag(product.image.thumbs), product_path(product, recommdend_by: @recommender)
      .title
        = link_to product.title.truncate(40), product_path(product)
      .price
        = number_to_currency(product.price,  unit: "₽ ", precision: 0)

app/views/categories/cat_urls.js.erb
<% rec = @recommender %>
<% redner_category_template = render 'categories/recommender.js.erb', recommender: @recommender %>
<% case rec %>
  <% when 'popular' %>
    var recommender = 'popular'
    <%= redner_category_template %>
  <% when 'recently_viewed'%>
    var recommender = 'recently_viewed'
    <%= redner_category_template %>
  <% when 'interesting' %>
    var recommender = 'interesting'
    <%= redner_category_template  %>
<% end %>

app/views/categories/edit.slim
.col-xs-10.col-xs-offset-1
  h1 Редактировать Категория
  = render 'form'

app/views/categories/get_urls.js.erb
<% if (@recommender == 'popular') %>
  jQuery('#recommender_popular').html("<%= j render(partial: 'rees46_popular.slim', locals: { products: @products, recommender: @recommender }) %>");
<% end %>

<% if (@recommender == 'recently_viewed') %>
  jQuery('#recommender_recently_viewed').html("<%= j render(partial: 'rees46_recently_viewed.slim', locals: { products: @products, recommender: @recommender }) %>");
<% end %>

<% if (@recommender == 'interesting') %>
  jQuery('#recommender_interesting').html("<%= j render(partial: 'rees46_interesting.slim', locals: { products: @products, recommender: @recommender }) %>");
<% end %>

app/views/categories/index.slim
.container
  .row.category-list-header
    .col-md-6
      h1 = t('category.header-title')
    .col-md-6.create-category-button
      = link_to new_category_path, :class => 'btn btn-success pull-right' do
        .i.fa.fa-plus.fa-lg
          = t('category.new_category')

  table.table.table-bordered.table-striped
    thead
      tr
    tbody
      = render "index"

app/views/categories/show.slim
ol.breadcrumb
  - for category in @category.ancestors.reverse
    li= link_to category.name, category

h1.text-center
  = @category.name

div class="rees46-recommend" data-type="popular" data-limit="12" data-title="Популярные товары" data-category="#{@category.id}"

.row
  = render partial: 'categories/product_categories',collection: @products.where(category_id: @category.id), as: :product
.row
  - @category.children.each do |child|
    - if !child.products.empty?
      .category_title
        h1= link_to child.name, category_path(child)
      .multiple-items
        = render partial: 'categories/product_categories', collection: @products.where(category_id: child), as: :product

    - if !child.children.product.empty?
      .category_title
        h1= link_to child.name, category_path(child)
        .multiple-items
          = render partial: 'categories/product_categories', collection: @products.where(category_id: child.children), as: :product

.clr

div class="rees46-recommend" data-type="recently_viewed" data-limit="12" data-title="Вы недавно смотрели"
div class="rees46-recommend" data-type="interesting" data-limit="12" data-title="Возможно, вам это понравится"