config/routes.rb
Rails.application.routes.draw do
  resources :orders

  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :users
  root 'store#index'

  get 'dashboard' => 'store#dashboard'

  get 'recommendations' => 'recommendations#rees46_recommender'

  resources :categories

  resources :brands

  resources :products do
    collection { post :import }
  end

  resources :line_items, only: [:create, :destroy] do
    get 'increment', on: :member
    get 'decrement', on: :member
  end

  resources :carts, only: [:index, :show, :destroy]

  resources :parsers, only: :index
  get 'store/xml_rees46'
end

app/views/layouts/_cart_total_quantity.slim
li
  .header_cart
    - if !@cart.try(:line_items).nil?
      = link_to cart_path(@cart)
        span.cart-count
          span.glyphicon.glyphicon-shopping-cart
          span#line_count = "#{@cart.line_items.size}"
    - else
      span.cart-count
        span.glyphicon.glyphicon-shopping-cart
        span#line_count = "0"

app/views/layouts/_categories_menu.slim
li.dropdown class="#{active_class(category_path(category))}"
  = link_to category.name, category_path(category)
  - if category.children.any?
    ul.dropdown-menu role='menu' aria-labelledby='drop'
      - category.walk_tree do |c, level|
        li = link_to "#{c.name}", category_path(c), style: "padding-left: #{ level == 0 ? 0 : level * 0 }13px;", class: (level == 1 ? 'child-menu-icon' : '')

app/views/layouts/_footer.slim
footer
  .h-card
    .r-footer-navigation.visible-md-block.visible-lg-block
      .container-fluid
        .row
          .col-md-9.col-lg-6.col-lg-offset-2
            ul.r-footer-list
              li
                a[href="/faq"]
                  = t('footer_list.faq')
              li
                a[href="/blog"]
                  = t('footer.blog')
              li
                a[href="/documentation"]
                  = t('footer.documentation')
              li
                a[href="/contact"]
                  = t('footer.contacts')
              li
                a[href="/docs/offer"]
                  = t('footer.contract_offer')
          .col-md-3.col-lg-2
            .r-si
              a.i.fa.fa-vk.fa-2x[aria-hidden="true" href="http://vk.com/p13n_ru"]
              a.i.fa.fa-facebook-official.fa-2x[aria-hidden="true" href="https://www.facebook.com/p13n.ru"]
              a.i.fa.fa-twitter-square.fa-2x[aria-hidden="true" target="_blank" href="http://twitter.com/noff"]
              a.i.fa.fa-google-plus-square.fa-2x[aria-hidden="true" target="_blank" href="https://plus.google.com/+Rees46/posts"]
    .r-footer-info
      .container-fluid
        .row
          .col-md-12.col-lg-8.col-lg-offset-2
            .r-footer-contacts.r-footer-contacts_address
              address.p-adr
                = t('footer.address')
                br
                = t('footer.address_br')
            .r-footer-contacts.r-footer-contacts_phone.p-tel
              gisphone._gis-phone-highlight-wrap.js_gis-phone-highlight-wrap-22919627b65904fbf78724295e9467cc._gis-phone-highlight-phone-wrap[data-ph-parsed="true"]
                | +7 (812) 980-45-33
            .r-footer-contacts.r-footer-contacts_mail
              a[href="mailto:dz@rees46.com"]
                | dz@rees46.com
    .r-footer-copyright
      .container-fluid
        .row
          .col-md-6.col-lg-4.col-lg-offset-2
            .pull-left.r-responsive-float
              p.r-text-pale
                small
                  | Copyright © 
                  span.p-name
                    a.u-url.r-text-pale[href="https://rees46.com/"]
                      | REES46
                  | , 2016 
          .col-md-6.col-lg-4
            .pull-right.r-responsive-float
              a.r-kechinov.p-org.r-text-pale[target="_blank" href="http://mkechinov.ru/"]
                = t('footer.kechinov_br')
                br
                = t('footer.kechinov')

app/views/layouts/_header.slim
header
  nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"]
          span.sr-only
          span.icon-bar
          span.icon-bar
          span.icon-bar
        .navbar-brand
          = link_to image_tag('rees46-logo.png'), root_path, class: "logo"
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav
          = render collection: @menu_categories, partial: "layouts/categories_menu", as: :category
        ul.nav.navbar-nav.navbar-right
          = render "layouts/cart_total_quantity"
          li.dropdown
            - if user_signed_in?
              a#drop.dropdown-toggle href='#' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'
                = current_user.email
                  span.caret
              ul.dropdown-menu role='menu' aria-labelledby='drop'
                li= link_to t('user_menu.destroy_user_session'), destroy_user_session_path, :method=>'delete'
                li= link_to t('user_menu.edit_user_registration'), edit_user_registration_path
                - if current_user.has_role? :admin
                  li = link_to t('user_menu.dashboard'), dashboard_path
            - else
              li = link_to t('user_menu.login'), new_user_session_path
              li = link_to t('user_menu.singup'), new_user_registration_path

app/views/layouts/_init.slim
javascript:
  $(function(){
    var callback;
    if (typeof(afterInitRees46) === 'function') {
      callback = afterInitRees46
    } else {
      callback = function() {}
    };

    function initREES46 () {
      var user_data = JSON.parse('#{j current_user.to_json(only: [:id, :email]).html_safe}');
      REES46.init('357382bf66ac0ce2f1722677c59511', user_data, callback);
    };

    var script = document.createElement('script');
    script.src = '//cdn.rees46.com/rees46_script2.js';
    script.async = true;
    script.onload = function() {
    var cart_product_ids = '#{ProductsInfo.new(@cart.try(:line_items) || []).product_ids_in_cart.to_json.html_safe}'
    initREES46();
      $('.rees46-recommend').each(function() {
        var dataType = $(this).attr('data-type');
        var dataLimit = $(this).attr('data-limit');
        var dataModification = $(this).attr('data-modification');
        var dataTitle = $(this).attr('data-title');
        var dataCategory = $(this).attr('data-category');
        REES46.addReadyListener(function () {

          var params = {
            recommender_type: dataType,
            item: '#{@product.try(:id)}',
            cart: JSON.parse(cart_product_ids).map(function (el) {
              return el.cart
            }),
            limit: dataLimit,
            modification: dataModification,
          };

          if(dataCategory) {
            params['categories'] = dataCategory;
          }

          REES46.recommend(params ,function(data) {
            if (data.length > 0) {
              $.ajax({
                type: 'GET',
                url: '/recommendations',
                data: {ids: data, recommended_by: dataType, recommended_title: dataTitle},
              });
              return false
            };
          });
        });
      });
    };
    $('head')[0].appendChild(script);
  });

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    title= content_for?(:title) ? yield(:title) : t('root_title')
    = csrf_meta_tags
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /![if lt IE 9]
    script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"
    script src="https://unpkg.com/flickity@1.2/dist/flickity.pkgd.min.js"
    link href="https://unpkg.com/flickity@1.2/dist/flickity.min.css" rel="stylesheet"
    = stylesheet_link_tag "application", :media => "all"
    /! For third-generation iPad with high-resolution Retina display:
    /! Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    /! For iPhone with high-resolution Retina display:
    /! Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    /! For first- and second-generation iPad:
    /! Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    /! For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    /! Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    /! For all other devices
    /! Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  body
    = render "layouts/header"
    .container
      .row
        = bootstrap_flash
        = yield
    = render "layouts/footer"
    = render "layouts/init.slim"
javascript:
  $(document).ready(function(){
    $(document).trigger("last-element-rendered");
  });

  // mk: for new type of cards
  $(document).ready(function () {
    $('.r-product_card').height($('.r-product_card').width());
    $(window).resize(function () {
      $('.r-product_card').height($('.r-product_card').width());
    });
  });

app/views/layouts/application.slim
doctype html
html lang="en"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    title= content_for?(:title) ? yield(:title) : t('root_title')
    = csrf_meta_tags
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /![if lt IE 9]
    script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"
    script src="https://npmcdn.com/flickity@1.2/dist/flickity.pkgd.min.js"
    link href="https://npmcdn.com/flickity@1.2/dist/flickity.min.css" rel="stylesheet"
    = stylesheet_link_tag "application", :media => "all"
    /! For third-generation iPad with high-resolution Retina display:
    /! Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    /! For iPhone with high-resolution Retina display:
    /! Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    /! For first- and second-generation iPad:
    /! Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    /! For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    /! Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    /! For all other devices
    /! Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  body
    = render "layouts/header"
    .container
      .row
        .span9
          = bootstrap_flash
          = yield
    = render "layouts/footer"
    = render "layouts/init.slim"
javascript:
  $(document).ready(function(){
    $(document).trigger("last-element-rendered");
  });